[platformio]
boards_dir = ../MeshCore/boards

[env:promicro_nrf52840_uart]
platform = nordicnrf52
board = promicro_nrf52840
framework = arduino
build_flags =
  -DUSE_TINYUSB
platform_packages =
  framework-arduinoadafruitnrf52 @ 1.10700.0
monitor_speed = 115200

[env:adafruit_qt_py_m0_uart]
platform = atmelsam
board = adafruit_qt_py_m0
framework = arduino
lib_deps = adafruit/Adafruit NeoPixel @ ^1.12.5
lib_ignore = Adafruit TinyUSB Library
monitor_speed = 115200

[env:nanoatmega328_uart]
platform = atmelavr
board = nanoatmega328
framework = arduino
lib_ignore = Adafruit TinyUSB Library
monitor_speed = 115200
